# Generated by Django 6.0.7 on 2026-07-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите адрес почты", max_length=50, unique=True, verbose_name="Почта"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, help_text="Введите телефон", max_length=50, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="Введите город", max_length=100, null=True, verbose_name="Город"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите ваш аватар",
                        null=True,
                        upload_to="users/avatars",
                        verbose_name="Аватар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
