# Generated by Django 6.0.7 on 2026-08-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(default=0, help_text="Укажите цену курса", verbose_name="Цена"),
            preserve_default=False,
        ),
    ]
